name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Start a simple web server to serve your application
      myapp:
        image: node:14
        ports:
          - 3000:3000
        working_dir: /app
        volumes:
          - .:/app
        command: ["npm", "start"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start the application
        run: npm start & # Start your application in the background

      - name: Wait for the application to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000; then
              echo "Application is ready!"
              break
            fi
            echo "Waiting for application to be ready..."
            sleep 10
          done

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
